baseurl = "/"
languageCode = 'en-us'
title = 'Android Malware Analysis'
theme = 'terminal'
googleAnalytics = 'G-P1SJVVX6K1'

[params]
  contentTypeName = "posts"
  showMenuItems = 2
  
  fullWidthTheme = false
  centerTheme = true
  Toc = true
  readingTime = false

  GitHubUser = 'xmpf'
  TwitterUser = 'megatr0nz'
  author = '0x1shtar'

  [params.widgets]
    search = true
    tags = true
    categories = true

[markup]

  [markup.tableOfContents]
    endLevel = 8
    startLevel = 1

  [markup.highlight]
    style = "monokai"
    codeFences = true
    tabWidth = 2
    lineNoStart = 1

[permalinks]
  posts = '/:title:/'

